version: '3'
services:
  backend:
    build: ./doctor-office-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build: 
      context: ./doctor-office-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
