apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: devanshnanani/virtualizationmidterm_backend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: 3000
        #  initialDelaySeconds: 10
        #  periodSeconds: 5
        #readinessProbe:
        #  httpGet:
        #    path: /health
        #    port: 3000
        #  initialDelaySeconds: 40
        #  periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
