apiVersion: v1
kind: PersistentVolume
metadata:
  name: doctor-app-pv
spec: 
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-09edaec62a671973e    
